### PR TITLE
update presentation section (pre-Hacktoberfest)

### PR DESCRIPTION
**Pull request by jdstelly**
Sorry for how late this is - I'd been giving my new job 101% effort. I didn't notice at the time of my PR review with Jeff (#25) that the old presentation section somehow snuck itself back in. This is the corrected presentation section.

### CODE REVIEW

**Comment by jdstelly** [comment]
Ugh.. looks like I accidentally included package-lock.json. Pretty sure that doesn't belong here. I'll try to find a way to remove that from the PR.

**Comment by jdstelly** [comment]
..and we're at 2 commits again. Let's see if I learned anything from #25. Squash pending.

**Comment by jdstelly** [comment]
I.. I think I did it! I should probably start donning a safety helmet before I start PRs.

**Review by jsquyres — COMMENTED** [review]
Can you `git commit --amend` to fix up the commit message?  Right now, it talks about removing `package-lock.json`, but that file is not part of this commit (it *was*, but you squashed it out -- so you don't need to mention it in the commit message).

**Comment by jdstelly** [comment]
Comparing f124c2e to 6407243, it looks like I resolved that commit message issue.

**Review by jsquyres — APPROVED** [review]

**Pull request merged**
