### PR TITLE
Consolidate Presentations, Resources. Expand archive scope language.

### PR DESCRIPTION
**Pull request by jdstelly**
My first amended PR, so I had a bit of trouble getting it on track again. Messy. During troubleshooting, I made a superficial change to grammar here or there to allow a commit. Let me know if these changes are in line with your requests referenced in #24 . Best practice probably isn't to open a new PR. I'll have to do some homework.

Respectfully,

J. Stelly

### CODE REVIEW

**Review by jsquyres — COMMENTED** [review]
Looks good now!

A few things:

1. You're right; you don't need to close a PR and open a new one just to make changes.  You can just push commits to your fork branch, and the PR will automatically update to show the current state of your fork branch.  E.g., you can push new commits to the fork branch, and they'll show up on the PR.
2. You also don't have to sign your github comments like an email. 😄 
3. Can you squash the 3 commits on this PR down to 1?  You can use a git interactive rebase -- `git rebase -i origin/master` to squash the 3 commits down to 1.  Google around for instructions on the git interactive rebase.

**Comment by jdstelly** [comment]
Alright, that was an adventure. I think it's straightened out now.

=======
Name: J. Stelly
Rank: GitNub
Posts: 11
Favorite Color: Blue
Quote: "_Opportunities are like sunrises - if you wait too long, you miss them_."

(Just kidding haha, I really appreciate your patience and guidance.)

**Comment by jdstelly** [comment]
I.. think I messed that up. It had just one commit, but now it has two. I'll dig into why this happened and try to fix it. Thanks for your patience.

**Comment by jdstelly** [comment]
Well this seems even worse. My instinct is to delete the entire fork, pull a fresh version of the KYOSS repo, and start over with a new branch and PR, but I wouldn't really learn if I did that (and I'd clutter up the PR history, I suspect). I'll have to step away for a few hours, but I'll try to figure out how I keep this PR at 1 commit.

**Comment by jsquyres** [comment]
Nah, don't delete your fork -- you don't need to do that.

You should be able to use `git rebase -i ...` and the "s"quash or "f"ixup functionality to squash the 3 commits into 1.  Then you'll need to force push up to your branch on your fork (because by squashing, you're changing git history -- making you use a "force push" is github's way of making you say "Yes, I know I'm changing history and I'm sure that this is what I want to do").

**Comment by jdstelly** [comment]
> Nah, don't delete your fork -- you don't need to do that.
> 
> You should be able to use `git rebase -i ...` and the "s"quash or "f"ixup functionality to squash the 3 commits into 1. Then you'll need to force push up to your branch on your fork (because by squashing, you're changing git history -- making you use a "force push" is github's way of making you say "Yes, I know I'm changing history and I'm sure that this is what I want to do").

I think at some point I botched your recommendation of `git rebase -i origin/master` because the command didn't work, so I tried a few other things _(referencing many articles, who knows what I did lol - see soiledIt.txt for command history if you wanted to try to make sense of it_) before remembering that they moved away from "master" language a few years back. With `git rebase -i origin/main` I would get to that point where I had a unified 1 commit PR (those first 2 force pushes), but then when it was running tests it would result in a merge conflict, which would generate a 2nd commit message. I started digging into the merge conflict for a way to resolve it locally - it's confusing to me because the last push to KYOSS/website was by me from that same repo, so I was definitely up to date.. Now neither of the 2 extra commits appear when I open a rebase document.

KYOSS0

[soiledIt.txt](https://github.com/KYOSS/website/files/9332250/soiledIt.txt)

**Comment by jsquyres** [comment]
@jdstelly and I chatted on a webex and I walked him through fixing up this PR.  Huzzah!

**Pull request merged**
