### PR TITLE
update presentations for December meeting

### PR DESCRIPTION
**Pull request by jdstelly**
Sorry, running late with this one.

### CODE REVIEW

**Comment by jdstelly** [comment]
Build failure appears to be related to an open Vuepress issue:
https://github.com/vuejs/vuepress/issues/3096

**Comment by jsquyres** [comment]
Hey @InfoSec812 Any idea what's happening in this Vuepress CI installation failure?

**Comment by InfoSec812** [comment]
> Hey @InfoSec812 Any idea what's happening in this Vuepress CI installation failure?

Somebody (ME) set it up to use the beta-prerelease of vuepress. We should be using version 1.9.7 instead.

Change the devDependencies in the package.json to use `^1.9.7`.

**Review by jsquyres — APPROVED** [review]

**Comment by jdstelly** [comment]
Thanks for the help!

**Comment by jsquyres** [comment]
@InfoSec812 Sorry to bug -- CI passed after I updated the Vuepress version, but the deploy failed.  I don't have the cycles to dig into this at the moment -- could you have a look? https://github.com/KYOSS/website/actions/runs/3695383819/jobs/6257692639

**Comment by InfoSec812** [comment]
It appears to be running the wrong npm script `npm run build` instead of `npm run docs:build`. I will try to fix it when I have a few minutes this morning.

**Comment by jsquyres** [comment]
Huh.  Nominally, it looks like it's running the right thing:

https://github.com/KYOSS/website/blob/06a83f5daa05d09839358b1cfeb86c69567ed854/.github/workflows/build-and-deploy-gh_pages.yml#L18

**Comment by InfoSec812** [comment]
OK, it's fixed now.

DEVEN PHILLIPS

SENIOR ARCHITECT, RED HAT CLOUD NATIVE RUNTIMES PRACTICE
[image: https://www.redhat.com/]
<https://www.redhat.com/>

**Pull request merged**
